spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          clone-on-start: true
          default-label: master
server:
  port: ${PORT}
